### ISSUE TITLE
Problem with chromakey. Help me please!

### ISSUE THREAD

**Issue by sbabich** [IOL0ol1/EmguFFmpeg#1]
I add the new function in the MediaFilterGraph.cs

public MediaFilterContext AddChromaFilter(MediaFilter filter, string contextName = null)
        {
            MediaFilterContext filterContext = AddFilter(filter, _ =>
            {
                ffmpeg.av_opt_set(_, "color", "green", ffmpeg.AV_OPT_SEARCH_CHILDREN);
                ffmpeg.av_opt_set_double(_, "similarity", 0.1, ffmpeg.AV_OPT_SEARCH_CHILDREN);
                ffmpeg.av_opt_set_double(_, "blend", 0.2, ffmpeg.AV_OPT_SEARCH_CHILDREN);
            }, contextName);
            if (ffmpeg.avfilter_pad_get_type(filterContext.AVFilterContext.output_pads, 0) != AVMediaType.AVMEDIA_TYPE_VIDEO)
                throw new FFmpegException(FFmpegException.FilterTypeError);
            return filterContext;
        }

And try to call it 

filterGraph.AddChromaFilter(new MediaFilter("chromakey"));

But in 
filterGraph.Initialize();

I got a exception 

EmguFFmpeg.FFmpegException: 'FFmpeg error [-22] Invalid argument'

I do not upderstand what I am doing wrong :(

Please help me!!

**Comment by IOL0ol1** [comment]
In fact, the filter feature I just submitted, not perfect, I need some time.
I'll get back to you later.

**Comment by IOL0ol1** [comment]
i have add some filter example.
 you can see it at [PngChromekeyFilter](https://github.com/IOL0ol1/EmguFFmpeg/blob/master/EmguFFmpeg.Example/PngChromekeyFilter.cs) and [VideoChromekeyFilter](https://github.com/IOL0ol1/EmguFFmpeg/blob/master/EmguFFmpeg.Example/VideoChromekeyFilter.cs)
it's like ffmpeg filter command example [here](https://www.ffmpeg.org/ffmpeg-filters.html#Commands-21)

- for video input always start from **buffer** filter to end **buffersink** filter.

- for audio input always start from **abuffer** filter to end **abuffersink** filter.

- filters need to be connected after adding filters **(avfilter_link)**

filter graph in VideoChromekeyFilter like this:
```csharp
┌──────┐     ┌──────┐     ┌─────────┐     ┌─────────┐
│input0│---->│buffer│---->│chramekey│---->│         │
└──────┘     └──────┘     └─────────┘     │         │     ┌──────────┐     ┌──────┐
                                          │ overlay │---->│buffersink│---->│output│
┌──────┐     ┌──────┐                     │         │     └──────────┘     └──────┘
│input1│-----│buffer│-------------------->│         │
└──────┘     └──────┘                     └─────────┘
```
In fact, the implementation of ffmpeg is more complicated, and filters may be automatically inserted according to different command line parameters. see [configure_input_video_filter](https://www.ffmpeg.org/doxygen/trunk/ffmpeg__filter_8c_source.html#l00746) and [configure_output_video_filter](https://www.ffmpeg.org/doxygen/trunk/ffmpeg__filter_8c_source.html#l00454)

**Comment by sbabich** [comment]
Thank you!!!!!
