### ISSUE TITLE
How to open hardware acceleration

### ISSUE THREAD

**Issue by ChengYen-Tang** [IOL0ol1/EmguFFmpeg#10]
[optional] upload the media file that is in question.

ffmpeg version: 4.4

question:
How to open hardware acceleration in this package. (QSV or Cuda)

**Comment by IOL0ol1** [comment]
If you are using a ffmpeg dll that supports hardware acceleration(Note that the entire project may become a GPL license), 
you can specify a hardware decoder like [this](https://github.com/IOL0ol1/EmguFFmpeg/blob/04b742b78a0bad02d6b53c444c30ad88aa829b7d/examples/EmguFFmpeg.Example/DecodeVideoWithCustomCodecScaledToMat.cs#L38)

I don't think I did a good job of this part. I've been thinking of a whole new way.
