### ISSUE TITLE
[Question] How to parse a packet?

### ISSUE THREAD

**Issue by waylaa** [IOL0ol1/EmguFFmpeg#12]
Using the FFmpeg.Autogen library i can call ffmpeg.av_parser_parse2() but is there a method that does the same thing in this library without using pointers?

**Comment by IOL0ol1** [comment]
@Whatareyoulaughingat I'm currently focusing on the demultiplexing and codec sections (AVFormatContext, AVCodecContext).
There is no interface related to AVCodecParserContext yet.
But I do have this part of the intention, and of course it may take a long time.

**Comment by IOL0ol1** [comment]
@Whatareyoulaughingat 
update dev 
[MediaCodecParserContext](https://github.com/IOL0ol1/EmguFFmpeg/blob/dev/src/MediaCodec/MediaCodecParserContext.cs)
[decodevideo example](https://github.com/IOL0ol1/EmguFFmpeg/blob/dev/example/FFmpegSharp.Example/DecodeVideo.cs)
