### ISSUE TITLE
An error in Mp4VideoWriter

### ISSUE THREAD

**Issue by yghipw** [IOL0ol1/EmguFFmpeg#5]
Thank you very much.
I used this library, It helped me a lot. 
I found an error In the WriteAudioFrame method line 143
` foreach (var packet in writer[videoIndex].WriteFrame(dstframe))`

I think it should be audioIndex

**Comment by IOL0ol1** [comment]
> Thank you very much.
> I used this library, It helped me a lot.
> I found an error In the WriteAudioFrame method line 143
> ` foreach (var packet in writer[videoIndex].WriteFrame(dstframe))`
> 
> I think it should be audioIndex

updated
